namespace FBI.Network
{
  public enum ErrorMessage
  {
    SUCCESS,
    NOT_FOUND,
    ALREADY_EXIST,
    SYSTEM,
    NOT_IMPLEMENTED,
    INVALID_ATTRIBUTE,
    PERMISSION_DENIED,
    DEPENDENT_PARENT,
    NAME_ALREADY_USED,
    SYNTAX,
    VERSION_MISMATCH
  };
}