//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public uint version_id {
            get {
                return ((uint)(this["version_id"]));
            }
            set {
                this["version_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double tablesFontSize {
            get {
                return ((double)(this["tablesFontSize"]));
            }
            set {
                this["tablesFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.5")]
        public float dgvFontSize {
            get {
                return ((float)(this["dgvFontSize"]));
            }
            set {
                this["dgvFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string user {
            get {
                return ((string)(this["user"]));
            }
            set {
                this["user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool controllingUIResizeTofitGrid {
            get {
                return ((bool)(this["controllingUIResizeTofitGrid"]));
            }
            set {
                this["controllingUIResizeTofitGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color titleFontColor {
            get {
                return ((global::System.Drawing.Color)(this["titleFontColor"]));
            }
            set {
                this["titleFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkSlateBlue")]
        public global::System.Drawing.Color titleBackColor {
            get {
                return ((global::System.Drawing.Color)(this["titleBackColor"]));
            }
            set {
                this["titleBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool titleFontBold {
            get {
                return ((bool)(this["titleFontBold"]));
            }
            set {
                this["titleFontBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool titleFontItalic {
            get {
                return ((bool)(this["titleFontItalic"]));
            }
            set {
                this["titleFontItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool titleBordersPresent {
            get {
                return ((bool)(this["titleBordersPresent"]));
            }
            set {
                this["titleBordersPresent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint titleIndent {
            get {
                return ((uint)(this["titleIndent"]));
            }
            set {
                this["titleIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color importantFontColor {
            get {
                return ((global::System.Drawing.Color)(this["importantFontColor"]));
            }
            set {
                this["importantFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color importantBackColor {
            get {
                return ((global::System.Drawing.Color)(this["importantBackColor"]));
            }
            set {
                this["importantBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool importantFontBold {
            get {
                return ((bool)(this["importantFontBold"]));
            }
            set {
                this["importantFontBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool importantFontItalic {
            get {
                return ((bool)(this["importantFontItalic"]));
            }
            set {
                this["importantFontItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool importantBordersPresent {
            get {
                return ((bool)(this["importantBordersPresent"]));
            }
            set {
                this["importantBordersPresent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color importantBordersColor {
            get {
                return ((global::System.Drawing.Color)(this["importantBordersColor"]));
            }
            set {
                this["importantBordersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color normalFontColor {
            get {
                return ((global::System.Drawing.Color)(this["normalFontColor"]));
            }
            set {
                this["normalFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color normalBackColor {
            get {
                return ((global::System.Drawing.Color)(this["normalBackColor"]));
            }
            set {
                this["normalBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool normalFontBold {
            get {
                return ((bool)(this["normalFontBold"]));
            }
            set {
                this["normalFontBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool normalFontItalic {
            get {
                return ((bool)(this["normalFontItalic"]));
            }
            set {
                this["normalFontItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool normalBordersPresent {
            get {
                return ((bool)(this["normalBordersPresent"]));
            }
            set {
                this["normalBordersPresent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public uint normalIndent {
            get {
                return ((uint)(this["normalIndent"]));
            }
            set {
                this["normalIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color normalBordersColor {
            get {
                return ((global::System.Drawing.Color)(this["normalBordersColor"]));
            }
            set {
                this["normalBordersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool detailFontBold {
            get {
                return ((bool)(this["detailFontBold"]));
            }
            set {
                this["detailFontBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool detailFontItalic {
            get {
                return ((bool)(this["detailFontItalic"]));
            }
            set {
                this["detailFontItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool detailBordersPresent {
            get {
                return ((bool)(this["detailBordersPresent"]));
            }
            set {
                this["detailBordersPresent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public uint detailIndent {
            get {
                return ((uint)(this["detailIndent"]));
            }
            set {
                this["detailIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color detailBordersColor {
            get {
                return ((global::System.Drawing.Color)(this["detailBordersColor"]));
            }
            set {
                this["detailBordersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint importantIndent {
            get {
                return ((uint)(this["importantIndent"]));
            }
            set {
                this["importantIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DodgerBlue")]
        public global::System.Drawing.Color detailFontColor {
            get {
                return ((global::System.Drawing.Color)(this["detailFontColor"]));
            }
            set {
                this["detailFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 255")]
        public global::System.Drawing.Color detailBackColor {
            get {
                return ((global::System.Drawing.Color)(this["detailBackColor"]));
            }
            set {
                this["detailBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PowderBlue")]
        public global::System.Drawing.Color FactsEditionInputsFillColor {
            get {
                return ((global::System.Drawing.Color)(this["FactsEditionInputsFillColor"]));
            }
            set {
                this["FactsEditionInputsFillColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color FactsEditionInputsTextColor {
            get {
                return ((global::System.Drawing.Color)(this["FactsEditionInputsTextColor"]));
            }
            set {
                this["FactsEditionInputsTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color FactsEditionOutputsBackColor {
            get {
                return ((global::System.Drawing.Color)(this["FactsEditionOutputsBackColor"]));
            }
            set {
                this["FactsEditionOutputsBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color FactsEditionOutputsTextColor {
            get {
                return ((global::System.Drawing.Color)(this["FactsEditionOutputsTextColor"]));
            }
            set {
                this["FactsEditionOutputsTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34")]
        public uint currentCurrency {
            get {
                return ((uint)(this["currentCurrency"]));
            }
            set {
                this["currentCurrency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string chart1Serie1AccountId {
            get {
                return ((string)(this["chart1Serie1AccountId"]));
            }
            set {
                this["chart1Serie1AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string chart1Serie2AccountId {
            get {
                return ((string)(this["chart1Serie2AccountId"]));
            }
            set {
                this["chart1Serie2AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("89")]
        public string chart2Serie1AccountId {
            get {
                return ((string)(this["chart2Serie1AccountId"]));
            }
            set {
                this["chart2Serie1AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string chart2Serie2AccountId {
            get {
                return ((string)(this["chart2Serie2AccountId"]));
            }
            set {
                this["chart2Serie2AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("349")]
        public string chart3Serie1AccountId {
            get {
                return ((string)(this["chart3Serie1AccountId"]));
            }
            set {
                this["chart3Serie1AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41")]
        public string chart3Serie2AccountId {
            get {
                return ((string)(this["chart3Serie2AccountId"]));
            }
            set {
                this["chart3Serie2AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("358")]
        public string chart4Serie1AccountId {
            get {
                return ((string)(this["chart4Serie1AccountId"]));
            }
            set {
                this["chart4Serie1AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("353")]
        public string chart4Serie2AccountId {
            get {
                return ((string)(this["chart4Serie2AccountId"]));
            }
            set {
                this["chart4Serie2AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public string chart1Serie1Color {
            get {
                return ((string)(this["chart1Serie1Color"]));
            }
            set {
                this["chart1Serie1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 128, 255")]
        public string chart1Serie2Color {
            get {
                return ((string)(this["chart1Serie2Color"]));
            }
            set {
                this["chart1Serie2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public string chart2Serie1Color {
            get {
                return ((string)(this["chart2Serie1Color"]));
            }
            set {
                this["chart2Serie1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 192")]
        public string chart2Serie2Color {
            get {
                return ((string)(this["chart2Serie2Color"]));
            }
            set {
                this["chart2Serie2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaleTurquoise")]
        public string chart3Serie1Color {
            get {
                return ((string)(this["chart3Serie1Color"]));
            }
            set {
                this["chart3Serie1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public string chart3Serie2Color {
            get {
                return ((string)(this["chart3Serie2Color"]));
            }
            set {
                this["chart3Serie2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 128")]
        public string chart4Serie1Color {
            get {
                return ((string)(this["chart4Serie1Color"]));
            }
            set {
                this["chart4Serie1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 255, 128")]
        public string chart4Serie2Color {
            get {
                return ((string)(this["chart4Serie2Color"]));
            }
            set {
                this["chart4Serie2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart1Serie1Type {
            get {
                return ((string)(this["chart1Serie1Type"]));
            }
            set {
                this["chart1Serie1Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart1Serie2Type {
            get {
                return ((string)(this["chart1Serie2Type"]));
            }
            set {
                this["chart1Serie2Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart2Serie1Type {
            get {
                return ((string)(this["chart2Serie1Type"]));
            }
            set {
                this["chart2Serie1Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart2Serie2Type {
            get {
                return ((string)(this["chart2Serie2Type"]));
            }
            set {
                this["chart2Serie2Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart3Serie1Type {
            get {
                return ((string)(this["chart3Serie1Type"]));
            }
            set {
                this["chart3Serie1Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart3Serie2Type {
            get {
                return ((string)(this["chart3Serie2Type"]));
            }
            set {
                this["chart3Serie2Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart4Serie1Type {
            get {
                return ((string)(this["chart4Serie1Type"]));
            }
            set {
                this["chart4Serie1Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart4Serie2Type {
            get {
                return ((string)(this["chart4Serie2Type"]));
            }
            set {
                this["chart4Serie2Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Résultat Opérationnel (m€)")]
        public string chart1Title {
            get {
                return ((string)(this["chart1Title"]));
            }
            set {
                this["chart1Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Investissements (m€)")]
        public string chart2Title {
            get {
                return ((string)(this["chart2Title"]));
            }
            set {
                this["chart2Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cash Flow (€)")]
        public string chart3Title {
            get {
                return ((string)(this["chart3Title"]));
            }
            set {
                this["chart3Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ratios Financiers (%)")]
        public string chart4Title {
            get {
                return ((string)(this["chart4Title"]));
            }
            set {
                this["chart4Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4242")]
        public ushort port_number {
            get {
                return ((ushort)(this["port_number"]));
            }
            set {
                this["port_number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52.19.112.46")]
        public string serverIp {
            get {
                return ((string)(this["serverIp"]));
            }
            set {
                this["serverIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color titleBordersColor {
            get {
                return ((global::System.Drawing.Color)(this["titleBordersColor"]));
            }
            set {
                this["titleBordersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int processId {
            get {
                return ((int)(this["processId"]));
            }
            set {
                this["processId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint language {
            get {
                return ((uint)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("223, 106, 120")]
        public global::System.Drawing.Color FactsEditionInputsRedFill {
            get {
                return ((global::System.Drawing.Color)(this["FactsEditionInputsRedFill"]));
            }
            set {
                this["FactsEditionInputsRedFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 192, 192")]
        public global::System.Drawing.Color FactsEditionOutputsRedFill {
            get {
                return ((global::System.Drawing.Color)(this["FactsEditionOutputsRedFill"]));
            }
            set {
                this["FactsEditionOutputsRedFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102, 199, 150")]
        public global::System.Drawing.Color FactsEditionInputCommitedFill {
            get {
                return ((global::System.Drawing.Color)(this["FactsEditionInputCommitedFill"]));
            }
            set {
                this["FactsEditionInputCommitedFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207, 237, 222")]
        public global::System.Drawing.Color FactsEditionOutputCommitedFill {
            get {
                return ((global::System.Drawing.Color)(this["FactsEditionOutputCommitedFill"]));
            }
            set {
                this["FactsEditionOutputCommitedFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PowderBlue")]
        public global::System.Drawing.Color FactsEditionDimensionsFill {
            get {
                return ((global::System.Drawing.Color)(this["FactsEditionDimensionsFill"]));
            }
            set {
                this["FactsEditionDimensionsFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeWeekEnds {
            get {
                return ((bool)(this["includeWeekEnds"]));
            }
            set {
                this["includeWeekEnds"] = value;
            }
        }
    }
}
