//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint version_id {
            get {
                return ((uint)(this["version_id"]));
            }
            set {
                this["version_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string tablesFontSize {
            get {
                return ((string)(this["tablesFontSize"]));
            }
            set {
                this["tablesFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.5")]
        public string dgvFontSize {
            get {
                return ((string)(this["dgvFontSize"]));
            }
            set {
                this["dgvFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string user {
            get {
                return ((string)(this["user"]));
            }
            set {
                this["user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string controllingUIResizeTofitGrid {
            get {
                return ((string)(this["controllingUIResizeTofitGrid"]));
            }
            set {
                this["controllingUIResizeTofitGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string titleFontColor {
            get {
                return ((string)(this["titleFontColor"]));
            }
            set {
                this["titleFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkSlateBlue")]
        public string titleBackColor {
            get {
                return ((string)(this["titleBackColor"]));
            }
            set {
                this["titleBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string titleFontBold {
            get {
                return ((string)(this["titleFontBold"]));
            }
            set {
                this["titleFontBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string titleFontItalic {
            get {
                return ((string)(this["titleFontItalic"]));
            }
            set {
                this["titleFontItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string titleBordersPresent {
            get {
                return ((string)(this["titleBordersPresent"]));
            }
            set {
                this["titleBordersPresent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string titleIndent {
            get {
                return ((string)(this["titleIndent"]));
            }
            set {
                this["titleIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string importantFontColor {
            get {
                return ((string)(this["importantFontColor"]));
            }
            set {
                this["importantFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string importantBackColor {
            get {
                return ((string)(this["importantBackColor"]));
            }
            set {
                this["importantBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string importantFontBold {
            get {
                return ((string)(this["importantFontBold"]));
            }
            set {
                this["importantFontBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string importantFontItalic {
            get {
                return ((string)(this["importantFontItalic"]));
            }
            set {
                this["importantFontItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string importantBordersPresent {
            get {
                return ((string)(this["importantBordersPresent"]));
            }
            set {
                this["importantBordersPresent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string importantBordersColor {
            get {
                return ((string)(this["importantBordersColor"]));
            }
            set {
                this["importantBordersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string normalFontColor {
            get {
                return ((string)(this["normalFontColor"]));
            }
            set {
                this["normalFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string normalBackColor {
            get {
                return ((string)(this["normalBackColor"]));
            }
            set {
                this["normalBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string normalFontBold {
            get {
                return ((string)(this["normalFontBold"]));
            }
            set {
                this["normalFontBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string normalFontItalic {
            get {
                return ((string)(this["normalFontItalic"]));
            }
            set {
                this["normalFontItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string normalBordersPresent {
            get {
                return ((string)(this["normalBordersPresent"]));
            }
            set {
                this["normalBordersPresent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string normalIndent {
            get {
                return ((string)(this["normalIndent"]));
            }
            set {
                this["normalIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string normalBordersColor {
            get {
                return ((string)(this["normalBordersColor"]));
            }
            set {
                this["normalBordersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string detailFontBold {
            get {
                return ((string)(this["detailFontBold"]));
            }
            set {
                this["detailFontBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string detailFontItalic {
            get {
                return ((string)(this["detailFontItalic"]));
            }
            set {
                this["detailFontItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string detailBordersPresent {
            get {
                return ((string)(this["detailBordersPresent"]));
            }
            set {
                this["detailBordersPresent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string detailIndent {
            get {
                return ((string)(this["detailIndent"]));
            }
            set {
                this["detailIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string detailBordersColor {
            get {
                return ((string)(this["detailBordersColor"]));
            }
            set {
                this["detailBordersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string importantIndent {
            get {
                return ((string)(this["importantIndent"]));
            }
            set {
                this["importantIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DodgerBlue")]
        public string detailFontColor {
            get {
                return ((string)(this["detailFontColor"]));
            }
            set {
                this["detailFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 255")]
        public string detailBackColor {
            get {
                return ((string)(this["detailBackColor"]));
            }
            set {
                this["detailBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PowderBlue")]
        public string snapshotInputsBackColor {
            get {
                return ((string)(this["snapshotInputsBackColor"]));
            }
            set {
                this["snapshotInputsBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public string snapshotInputsTextColor {
            get {
                return ((string)(this["snapshotInputsTextColor"]));
            }
            set {
                this["snapshotInputsTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string snapshotOutputsBackColor {
            get {
                return ((string)(this["snapshotOutputsBackColor"]));
            }
            set {
                this["snapshotOutputsBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string snapshotOutputsTextColor {
            get {
                return ((string)(this["snapshotOutputsTextColor"]));
            }
            set {
                this["snapshotOutputsTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34")]
        public uint currentCurrency {
            get {
                return ((uint)(this["currentCurrency"]));
            }
            set {
                this["currentCurrency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string chart1Serie1AccountId {
            get {
                return ((string)(this["chart1Serie1AccountId"]));
            }
            set {
                this["chart1Serie1AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string chart1Serie2AccountId {
            get {
                return ((string)(this["chart1Serie2AccountId"]));
            }
            set {
                this["chart1Serie2AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("89")]
        public string chart2Serie1AccountId {
            get {
                return ((string)(this["chart2Serie1AccountId"]));
            }
            set {
                this["chart2Serie1AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string chart2Serie2AccountId {
            get {
                return ((string)(this["chart2Serie2AccountId"]));
            }
            set {
                this["chart2Serie2AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("349")]
        public string chart3Serie1AccountId {
            get {
                return ((string)(this["chart3Serie1AccountId"]));
            }
            set {
                this["chart3Serie1AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41")]
        public string chart3Serie2AccountId {
            get {
                return ((string)(this["chart3Serie2AccountId"]));
            }
            set {
                this["chart3Serie2AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("358")]
        public string chart4Serie1AccountId {
            get {
                return ((string)(this["chart4Serie1AccountId"]));
            }
            set {
                this["chart4Serie1AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("353")]
        public string chart4Serie2AccountId {
            get {
                return ((string)(this["chart4Serie2AccountId"]));
            }
            set {
                this["chart4Serie2AccountId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public string chart1Serie1Color {
            get {
                return ((string)(this["chart1Serie1Color"]));
            }
            set {
                this["chart1Serie1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 128, 255")]
        public string chart1Serie2Color {
            get {
                return ((string)(this["chart1Serie2Color"]));
            }
            set {
                this["chart1Serie2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public string chart2Serie1Color {
            get {
                return ((string)(this["chart2Serie1Color"]));
            }
            set {
                this["chart2Serie1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 192")]
        public string chart2Serie2Color {
            get {
                return ((string)(this["chart2Serie2Color"]));
            }
            set {
                this["chart2Serie2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaleTurquoise")]
        public string chart3Serie1Color {
            get {
                return ((string)(this["chart3Serie1Color"]));
            }
            set {
                this["chart3Serie1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public string chart3Serie2Color {
            get {
                return ((string)(this["chart3Serie2Color"]));
            }
            set {
                this["chart3Serie2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 128")]
        public string chart4Serie1Color {
            get {
                return ((string)(this["chart4Serie1Color"]));
            }
            set {
                this["chart4Serie1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 255, 128")]
        public string chart4Serie2Color {
            get {
                return ((string)(this["chart4Serie2Color"]));
            }
            set {
                this["chart4Serie2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart1Serie1Type {
            get {
                return ((string)(this["chart1Serie1Type"]));
            }
            set {
                this["chart1Serie1Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart1Serie2Type {
            get {
                return ((string)(this["chart1Serie2Type"]));
            }
            set {
                this["chart1Serie2Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart2Serie1Type {
            get {
                return ((string)(this["chart2Serie1Type"]));
            }
            set {
                this["chart2Serie1Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart2Serie2Type {
            get {
                return ((string)(this["chart2Serie2Type"]));
            }
            set {
                this["chart2Serie2Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart3Serie1Type {
            get {
                return ((string)(this["chart3Serie1Type"]));
            }
            set {
                this["chart3Serie1Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart3Serie2Type {
            get {
                return ((string)(this["chart3Serie2Type"]));
            }
            set {
                this["chart3Serie2Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart4Serie1Type {
            get {
                return ((string)(this["chart4Serie1Type"]));
            }
            set {
                this["chart4Serie1Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string chart4Serie2Type {
            get {
                return ((string)(this["chart4Serie2Type"]));
            }
            set {
                this["chart4Serie2Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Résultat Opérationnel (m€)")]
        public string chart1Title {
            get {
                return ((string)(this["chart1Title"]));
            }
            set {
                this["chart1Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Investissements (m€)")]
        public string chart2Title {
            get {
                return ((string)(this["chart2Title"]));
            }
            set {
                this["chart2Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cash Flow (€)")]
        public string chart3Title {
            get {
                return ((string)(this["chart3Title"]));
            }
            set {
                this["chart3Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ratios Financiers (%)")]
        public string chart4Title {
            get {
                return ((string)(this["chart4Title"]));
            }
            set {
                this["chart4Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4242")]
        public int port_number {
            get {
                return ((int)(this["port_number"]));
            }
            set {
                this["port_number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52.19.112.46")]
        public string serverIp {
            get {
                return ((string)(this["serverIp"]));
            }
            set {
                this["serverIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string titleBordersColor {
            get {
                return ((string)(this["titleBordersColor"]));
            }
            set {
                this["titleBordersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int processId {
            get {
                return ((int)(this["processId"]));
            }
            set {
                this["processId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int language {
            get {
                return ((int)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
    }
}
