//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBI.Properties {


  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
  internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
  {

    private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

    public static Settings Default
    {
      get
      {
        return defaultInstance;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("5")]
    public int version_id
    {
      get
      {
        return ((int)(this["version_id"]));
      }
      set
      {
        this["version_id"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("8")]
    public float tablesFontSize
    {
      get
      {
        return ((float)(this["tablesFontSize"]));
      }
      set
      {
        this["tablesFontSize"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("8.5")]
    public float dgvFontSize
    {
      get
      {
        return ((float)(this["dgvFontSize"]));
      }
      set
      {
        this["dgvFontSize"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("root")]
    public string user
    {
      get
      {
        return ((string)(this["user"]));
      }
      set
      {
        this["user"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    public bool controllingUIResizeTofitGrid
    {
      get
      {
        return ((bool)(this["controllingUIResizeTofitGrid"]));
      }
      set
      {
        this["controllingUIResizeTofitGrid"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("White")]
    public global::System.Drawing.Color titleFontColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["titleFontColor"]));
      }
      set
      {
        this["titleFontColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("DarkSlateBlue")]
    public global::System.Drawing.Color titleBackColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["titleBackColor"]));
      }
      set
      {
        this["titleBackColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool titleFontBold
    {
      get
      {
        return ((bool)(this["titleFontBold"]));
      }
      set
      {
        this["titleFontBold"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool titleFontItalic
    {
      get
      {
        return ((bool)(this["titleFontItalic"]));
      }
      set
      {
        this["titleFontItalic"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool titleBordersPresent
    {
      get
      {
        return ((bool)(this["titleBordersPresent"]));
      }
      set
      {
        this["titleBordersPresent"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("0")]
    public int titleIndent
    {
      get
      {
        return ((int)(this["titleIndent"]));
      }
      set
      {
        this["titleIndent"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("Black")]
    public global::System.Drawing.Color importantFontColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["importantFontColor"]));
      }
      set
      {
        this["importantFontColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("White")]
    public global::System.Drawing.Color importantBackColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["importantBackColor"]));
      }
      set
      {
        this["importantBackColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool importantFontBold
    {
      get
      {
        return ((bool)(this["importantFontBold"]));
      }
      set
      {
        this["importantFontBold"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool importantFontItalic
    {
      get
      {
        return ((bool)(this["importantFontItalic"]));
      }
      set
      {
        this["importantFontItalic"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool importantBordersPresent
    {
      get
      {
        return ((bool)(this["importantBordersPresent"]));
      }
      set
      {
        this["importantBordersPresent"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("White")]
    public global::System.Drawing.Color importantBordersColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["importantBordersColor"]));
      }
      set
      {
        this["importantBordersColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("Black")]
    public global::System.Drawing.Color normalFontColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["normalFontColor"]));
      }
      set
      {
        this["normalFontColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("White")]
    public global::System.Drawing.Color normalBackColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["normalBackColor"]));
      }
      set
      {
        this["normalBackColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool normalFontBold
    {
      get
      {
        return ((bool)(this["normalFontBold"]));
      }
      set
      {
        this["normalFontBold"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool normalFontItalic
    {
      get
      {
        return ((bool)(this["normalFontItalic"]));
      }
      set
      {
        this["normalFontItalic"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool normalBordersPresent
    {
      get
      {
        return ((bool)(this["normalBordersPresent"]));
      }
      set
      {
        this["normalBordersPresent"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("2")]
    public int normalIndent
    {
      get
      {
        return ((int)(this["normalIndent"]));
      }
      set
      {
        this["normalIndent"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("White")]
    public global::System.Drawing.Color normalBordersColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["normalBordersColor"]));
      }
      set
      {
        this["normalBordersColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool detailFontBold
    {
      get
      {
        return ((bool)(this["detailFontBold"]));
      }
      set
      {
        this["detailFontBold"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool detailFontItalic
    {
      get
      {
        return ((bool)(this["detailFontItalic"]));
      }
      set
      {
        this["detailFontItalic"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("0")]
    public byte detailBordersPresent
    {
      get
      {
        return ((byte)(this["detailBordersPresent"]));
      }
      set
      {
        this["detailBordersPresent"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("3")]
    public int detailIndent
    {
      get
      {
        return ((int)(this["detailIndent"]));
      }
      set
      {
        this["detailIndent"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("White")]
    public global::System.Drawing.Color detailBordersColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["detailBordersColor"]));
      }
      set
      {
        this["detailBordersColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("1")]
    public int importantIndent
    {
      get
      {
        return ((int)(this["importantIndent"]));
      }
      set
      {
        this["importantIndent"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("DodgerBlue")]
    public global::System.Drawing.Color detailFontColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["detailFontColor"]));
      }
      set
      {
        this["detailFontColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 255")]
    public global::System.Drawing.Color detailBackColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["detailBackColor"]));
      }
      set
      {
        this["detailBackColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("PowderBlue")]
    public global::System.Drawing.Color snapshotInputsBackColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["snapshotInputsBackColor"]));
      }
      set
      {
        this["snapshotInputsBackColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
    public global::System.Drawing.Color snapshotInputsTextColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["snapshotInputsTextColor"]));
      }
      set
      {
        this["snapshotInputsTextColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("White")]
    public global::System.Drawing.Color snapshotOutputsBackColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["snapshotOutputsBackColor"]));
      }
      set
      {
        this["snapshotOutputsBackColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("Black")]
    public global::System.Drawing.Color snapshotOutputsTextColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["snapshotOutputsTextColor"]));
      }
      set
      {
        this["snapshotOutputsTextColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("34")]
    public int currentCurrency
    {
      get
      {
        return ((int)(this["currentCurrency"]));
      }
      set
      {
        this["currentCurrency"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("2")]
    public int chart1Serie1AccountId
    {
      get
      {
        return ((int)(this["chart1Serie1AccountId"]));
      }
      set
      {
        this["chart1Serie1AccountId"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("0")]
    public int chart1Serie2AccountId
    {
      get
      {
        return ((int)(this["chart1Serie2AccountId"]));
      }
      set
      {
        this["chart1Serie2AccountId"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("89")]
    public int chart2Serie1AccountId
    {
      get
      {
        return ((int)(this["chart2Serie1AccountId"]));
      }
      set
      {
        this["chart2Serie1AccountId"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("0")]
    public int chart2Serie2AccountId
    {
      get
      {
        return ((int)(this["chart2Serie2AccountId"]));
      }
      set
      {
        this["chart2Serie2AccountId"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("349")]
    public int chart3Serie1AccountId
    {
      get
      {
        return ((int)(this["chart3Serie1AccountId"]));
      }
      set
      {
        this["chart3Serie1AccountId"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("41")]
    public int chart3Serie2AccountId
    {
      get
      {
        return ((int)(this["chart3Serie2AccountId"]));
      }
      set
      {
        this["chart3Serie2AccountId"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("358")]
    public int chart4Serie1AccountId
    {
      get
      {
        return ((int)(this["chart4Serie1AccountId"]));
      }
      set
      {
        this["chart4Serie1AccountId"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("353")]
    public int chart4Serie2AccountId
    {
      get
      {
        return ((int)(this["chart4Serie2AccountId"]));
      }
      set
      {
        this["chart4Serie2AccountId"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
    public global::System.Drawing.Color chart1Serie1Color
    {
      get
      {
        return ((global::System.Drawing.Color)(this["chart1Serie1Color"]));
      }
      set
      {
        this["chart1Serie1Color"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("128, 128, 255")]
    public global::System.Drawing.Color chart1Serie2Color
    {
      get
      {
        return ((global::System.Drawing.Color)(this["chart1Serie2Color"]));
      }
      set
      {
        this["chart1Serie2Color"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
    public global::System.Drawing.Color chart2Serie1Color
    {
      get
      {
        return ((global::System.Drawing.Color)(this["chart2Serie1Color"]));
      }
      set
      {
        this["chart2Serie1Color"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 192")]
    public global::System.Drawing.Color chart2Serie2Color
    {
      get
      {
        return ((global::System.Drawing.Color)(this["chart2Serie2Color"]));
      }
      set
      {
        this["chart2Serie2Color"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("PaleTurquoise")]
    public global::System.Drawing.Color chart3Serie1Color
    {
      get
      {
        return ((global::System.Drawing.Color)(this["chart3Serie1Color"]));
      }
      set
      {
        this["chart3Serie1Color"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
    public global::System.Drawing.Color chart3Serie2Color
    {
      get
      {
        return ((global::System.Drawing.Color)(this["chart3Serie2Color"]));
      }
      set
      {
        this["chart3Serie2Color"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 128")]
    public global::System.Drawing.Color chart4Serie1Color
    {
      get
      {
        return ((global::System.Drawing.Color)(this["chart4Serie1Color"]));
      }
      set
      {
        this["chart4Serie1Color"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("128, 255, 128")]
    public global::System.Drawing.Color chart4Serie2Color
    {
      get
      {
        return ((global::System.Drawing.Color)(this["chart4Serie2Color"]));
      }
      set
      {
        this["chart4Serie2Color"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("10")]
    public int chart1Serie1Type
    {
      get
      {
        return ((int)(this["chart1Serie1Type"]));
      }
      set
      {
        this["chart1Serie1Type"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("10")]
    public int chart1Serie2Type
    {
      get
      {
        return ((int)(this["chart1Serie2Type"]));
      }
      set
      {
        this["chart1Serie2Type"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("10")]
    public int chart2Serie1Type
    {
      get
      {
        return ((int)(this["chart2Serie1Type"]));
      }
      set
      {
        this["chart2Serie1Type"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("10")]
    public int chart2Serie2Type
    {
      get
      {
        return ((int)(this["chart2Serie2Type"]));
      }
      set
      {
        this["chart2Serie2Type"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("10")]
    public int chart3Serie1Type
    {
      get
      {
        return ((int)(this["chart3Serie1Type"]));
      }
      set
      {
        this["chart3Serie1Type"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("10")]
    public int chart3Serie2Type
    {
      get
      {
        return ((int)(this["chart3Serie2Type"]));
      }
      set
      {
        this["chart3Serie2Type"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("10")]
    public int chart4Serie1Type
    {
      get
      {
        return ((int)(this["chart4Serie1Type"]));
      }
      set
      {
        this["chart4Serie1Type"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("10")]
    public int chart4Serie2Type
    {
      get
      {
        return ((int)(this["chart4Serie2Type"]));
      }
      set
      {
        this["chart4Serie2Type"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("Résultat Opérationnel (m€)")]
    public string chart1Title
    {
      get
      {
        return ((string)(this["chart1Title"]));
      }
      set
      {
        this["chart1Title"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("Investissements (m€)")]
    public string chart2Title
    {
      get
      {
        return ((string)(this["chart2Title"]));
      }
      set
      {
        this["chart2Title"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("Cash Flow (€)")]
    public string chart3Title
    {
      get
      {
        return ((string)(this["chart3Title"]));
      }
      set
      {
        this["chart3Title"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("Ratios Financiers (%)")]
    public string chart4Title
    {
      get
      {
        return ((string)(this["chart4Title"]));
      }
      set
      {
        this["chart4Title"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("4242")]
    public int port_number
    {
      get
      {
        return ((int)(this["port_number"]));
      }
      set
      {
        this["port_number"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("52.19.112.46")]
    public string serverIp
    {
      get
      {
        return ((string)(this["serverIp"]));
      }
      set
      {
        this["serverIp"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("Black")]
    public global::System.Drawing.Color titleBordersColor
    {
      get
      {
        return ((global::System.Drawing.Color)(this["titleBordersColor"]));
      }
      set
      {
        this["titleBordersColor"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("0")]
    public int processId
    {
      get
      {
        return ((int)(this["processId"]));
      }
      set
      {
        this["processId"] = value;
      }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("0")]
    public int language
    {
      get
      {
        return ((int)(this["language"]));
      }
      set
      {
        this["language"] = value;
      }
    }
  }
}
